### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by timsneath** [davidejones/winsnake#1]
Was looking for a couple of small Win32 sample apps and I came across yours. Wondering whether you might consider adding a `LICENSE` file to allow others to use it? BSD or MIT licenses would be ideal from my perspective, but obviously it's entirely up to you :)

Thanks!

**Comment by davidejones** [comment]
👋 Hey Tim, sure I've added the MIT license. I'd be interested to see what you are using it for if you get time to post back here with a link or description or anything 🙇

**Comment by timsneath** [comment]
Thank you so much for that! 

I'm creating a library for Win32 interop from Dart code (https://pub.dev/packages/win32). To both demonstrate the library and test performance / accuracy, I've been also porting over some manageable-sized [examples](https://github.com/timsneath/win32/tree/master/example) that demonstrate it in action. Your game uses some interesting APIs such as `StretchDIBits`, so I thought it was a good one to try out. 

I've [ported it across](https://github.com/timsneath/win32/blob/snake/example/snake.dart), but while it runs the rendering is broken at present, so I need to debug it before I add it to the main branch, at which point I'd like to include it as an example with due credit. 

Hope that's OK. Thanks for building it -- I've enjoyed learning from your code!

**Comment by davidejones** [comment]
Sure no problem. 
Nice work I'll definitely try it out and the other examples when I get some time. 

> Hope that's OK. Thanks for building it -- I've enjoyed learning from your code!

Of course! its always nice to see something you've made being used or improved. It was something i kind of threw together so apologies for the messy code. I'm sure you have learnt all kinds of ways not to do things from it 😆 

Good luck debugging the rendering and thanks for letting me know its use!
